### ISSUE TITLE
Only show one 'find my location' button 

### ISSUE THREAD

**Issue by aaronbrethorst** [goeuropa/onebusaway-react-webapp#6]
right now there are three 'find my location' buttons. there should only be one. probably the bottom left one.

<img width="832" alt="Screenshot 2024-06-17 at 8 20 07 PM" src="https://github.com/goeuropa/onebusaway-react-webapp/assets/2254/4821d885-bca6-4255-946f-eac725502f55">

**Comment by Michal-Radomski** [comment]
It is caused by React.StrictMode. Explanation is here: https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode
It's only in dev mode and  you can disable StrictMode by removing the <React.StrictMode> tag

![image](https://github.com/goeuropa/onebusaway-react-webapp/assets/77637565/a55fe7c5-3bef-4b40-9bd6-11f00d60c6a7)
